baseURL: "yashmaurya.com" 
title: Yash Maurya
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Archive
          url: archive/
          weight: 3 
        # - name: Recent
        #   url: recent/
        #   weight: 3 
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I'm a Privacy Engineering Graduate student at Carnegie Mellon University. I specialize in Privacy Enhancing Technologies(PETs) like Differential Privacy, Secure MPCs, Federated Learning, Explainable and Responsible AI"
    author: Yash Maurya
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yash Maurya
          subtitle: "<p>
  I'm a <strong>Privacy Engineering</strong> graduate student at
  <strong>Carnegie Mellon University</strong>.
</p>
<p>
  I'm dedicated to creating <strong>privacy-conscious</strong> AI solutions and ensuring the <strong>ethical</strong> use of data.<br>
  My mission is to design <strong>robust</strong> privacy systems for the greater good of society.
</p>
<p>
  My key interests include
  <strong>Privacy Preserving Machine Learning</strong>,
  <strong>Fairness</strong>,
  <strong>Federated Learning</strong>,
  <strong>Differential Privacy</strong>, and
  <strong>Explainable and Responsible AI</strong>.
</p>
"
          imageUrl: "/yash.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Yash Maurya
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            # - name: Data
            #   url: data/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: /resume.pdf
        - name: Email
          url: mailto:ymaurya@cs.cmu.edu
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=md0vz3wAAAAJ&hl=en
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/yashmaurya01
        - name: LinkedIn
          url: https://www.linkedin.com/in/yashmaurya/
        - name: Twitter
          url: https://twitter.com/yash_maurya01

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yash Maurya"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
